name: 'Pull Request Actions'

on:
  pull_request:
    # Only initiate the workflow when a PR is opened, or committed to.
    branches:
      - main

jobs:
  validateConfig:
    name: 'Validate Config'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Validation
        run: npx --yes --package renovate -- renovate-config-validator --strict
